apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoweb
  template:
    metadata:
      labels:
        app: contosoweb
    spec:
      containers:
      - name: contosoweb
        image: %AcrName%.azurecr.io/contosoweb:beta1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contosoweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: contosoweb